version: '3.0'
services:
  postgres:
    build: persistence/
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
  hasura:
    build: hasura/
    ports:
      - '8080:8080'
    restart: on-failure:10
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_DB_PASSWORD: password
      HASURA_GRAPHQL_DATABASE_URL: postgres://user:password@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    depends_on:
      - postgres
